export const LABELS: Record<string, string> = {
  REGISTERED: 'Inscrit',
  SEARCHING: 'En recherche',
  IN_PROCESS: 'En cours',
  SIGNED: 'Signe',
  ARCHIVED: 'Archive',
  PROSPECT: 'Prospect',
  PARTNER: 'Partenaire',
  INACTIVE: 'Inactif',
  DRAFT: 'Brouillon',
  ACTIVE: 'Active',
  CLOSED: 'Cloturee',
  EXPIRED: 'Expiree',
  PROPOSED: 'Propose',
  VIEWED: 'Vu',
  INTERVIEW_SCHEDULED: 'Entretien planifie',
  ACCEPTED: 'Accepte',
  REJECTED: 'Refuse',
  APPRENTICESHIP: 'Apprentissage',
  PROFESSIONAL: 'Professionnalisation',
};
